### ISSUE TITLE
Show Thank you/confirmation of submission screen after submission?

### ISSUE THREAD

**Issue by StephenAbbott** [okfn/crowdsourced-surveys#10]
During testing of the Ushahidi mobile form, I've noticed that users are sent to a world map after submitting their entry without any recognition/notification that their submission has been successful.

Is there functionality which would allow us to send them to a Thank you/acknowledgment screen rather than the empty map view?

**Comment by pwalsh** [comment]
As we are providing a custom, simplified view for crowdsourcing users, we can do this, and the task is covered in https://github.com/okfn/crowdsourced-surveys/issues/11

Closing this issue.
