### ISSUE TITLE
Ensure we have staging and production instances

### ISSUE THREAD

**Issue by pwalsh** [okfn/crowdsourced-surveys#14]
# Description

We need staging and production setups for data collection. I suggest we use the current setup for staging ( still requires https://github.com/okfn/crowdsourced-surveys/issues/11 ), and then set up a new platform, client, database and HTML wrapper for production use with a clean database, and all of our team as admins.

These should be with Heroku dynos at a paid level. Please do with @vitorbaptista 

# Tasks

- [x] Platform
- [x] Client
- [x] Database
  - [x] Use the DB backup/snapshot features provided. This is *critical*
- [ ] Custom domain + HTML wrapper

**Comment by nightsh** [comment]
@pwalsh could you clarify what do you mean by "Use the DB backup/snapshot features provided."?

Backups are available for the past 5 days in the cleardb settings, maybe you mean storing them into a safe(r?) place for longer?

**Comment by pwalsh** [comment]
@nightsh rolling 5 day backup is great. Maybe over feb, we will choose to persist some additional snapshots, but we can do that manually.

**Comment by pwalsh** [comment]
@nightsh done? Can close?
