### ISSUE TITLE
Generate dummy data

### ISSUE THREAD

**Issue by nightsh** [okfn/crowdsourced-surveys#3]
Assuming [milestone 1](https://github.com/okfn/crowdsourced-surveys/milestone/1) is closed in favour of running Ushahidi, we further need to populate the database with some realistic entries. This is likely the first coding task in the project :-)

- [x] write data generators according to structure defined in #2 
- [x] populate the database with generated data
- [ ] if possible, attempt using the forms created to populate the database (or write tests to make sure they don't break)

**Comment by pwalsh** [comment]
@nightsh what is the status of this?

**Comment by pwalsh** [comment]
@nightsh status?

**Comment by nightsh** [comment]
Closing, it's been fixed some time ago.
