### ISSUE TITLE
Data privacy - investigate if survey results could be made private

### ISSUE THREAD

**Issue by nightsh** [okfn/crowdsourced-surveys#5]

**Comment by nightsh** [comment]
@StephenAbbott here is some more detailed info regarding the privacy of collected data:

* contributions land in a "curation queue"
  * here they can be deleted, archived, held or published
* things that are published land on a public map
* things that are not published are only visible for logged in users

We are able to pull the data from Ushahidi using the API and some (authenticated) calls. Curators would probably have to determine the semantics of "archived" and "under review", i.e. "approved" posts are under review, archived means rejected, or the other way around. This way we can filter them when processing the curated data.

Or if nobody curates the data at all, then nothing has to be done. Everything is private until someone manually publishes it.

I'm gonna close this issue now, feel free to reopen if you think I missed anything relevant.

**Comment by StephenAbbott** [comment]
Thanks for checking into this, @nightsh. Good that contributions are not public until a curator explicitly published them. 

However, if I understand your notes, it sounds like there is not an option where a curator can approve data contributions without making that contribution public on a map. Is that correct? Is the map element automatically public?

From conversations with partners and knowing their sensitivities about data handling/publishing, I think the preference would be to have a way to approve contributions but for the approved data to remain private unless explicitly released by the Government of Tanzania. 

Right now, would they need to do a workaround where they would keep all contributions as held and delete/archive any unwanted contributions? Good to test this out once the process/tools are set up.

**Comment by nightsh** [comment]
@StephenAbbott I have some more info on this. Please let me know if it's okay:

* posts can be submitted by anyone
* all survey fields are marked as "private" so only logged in members with edit access to the survey can see them
* in the manual curation process, pressing "publish" to mark a submission as accepted does not put it on the public map, as the answers to all fields are marked as private (the location field is the most relevant here, for the map view)
* once logged in, if you don't have rights to edit the survey, you also cannot see the submitted answers

I think this is way closer to what is expected from this platform. What do you think? Feel free to close this issue if it sounds reasonable.

**Comment by StephenAbbott** [comment]
Thanks for this explanation, @nightsh. Just been having a look at the survey on desktop/mobile while not logged in and, like you say, I can't edit the survey or see anything on the map until I log in. But on the Data tab, I can see two published test reports - 'Not Tanzania' and 'some title'. So I'm guessing that publishing submissions puts them in the a public list under Data but doesn't add them to the Map. Is that expected?

Is there a way within the Ushahidi platform that the Map / Data / Activity / More footer, sidebar or links can be hidden for users directed to the form who aren't logged in? 

I'm trying to anticipate government partner demands based on past conversations with them, but I can imagine them preferring a form interface which does not show the Map / Data / Activity filter options to everyone as it could lead people to the impression that the users could download/view the data and our partners want to be in control of data publication/dissemination.

**Comment by pwalsh** [comment]
I think we can either:

1. Not use the publish feature.
2. Block access to `/views/` unless user is logged in.

I looked into the code to see how easy (2) would be, and it does not look straight forward.

Actions:

1. @nightsh please document that we don't use the publish feature as it publishes collected data, which in any given circumstance, may not be desired (we still do not know if this is an issue in the TZ case).
2. @nightsh please create an issue on the ushahidi platform or client repo, asking about existing settings or approaches to making `/views/*` accessible to logged in users only.

Once these are done, this issue can be closed.

**Comment by StephenAbbott** [comment]
Thanks @pwalsh. I agree that the most likely solution here would be to not use the publish feature unless we can change the mind of local partners in Tanzania. 

For my information, can I just check with @nightsh that we can still pull data contributions from the Ushahidi API if partners use 'held' to keep approved contributions rather than 'publish'? So workflow would be to 'delete' or 'archive' any unwanted posts and use 'held' for approved ones?

**Comment by pwalsh** [comment]
@nightsh can you respond to the question from @StephenAbbott so the issue can be closed.

**Comment by nightsh** [comment]
@StephenAbbott that is correct. If they "publish", the answers won't be visible on the map, and in the "Data" section they will be able to see the school name and ward. Due to limitations of the platform, we could not hide those, not unless we modify the client app.

However, anything else but the "published" answers will not be visible at all in any public view.
