### ISSUE TITLE
Translations for forms

### ISSUE THREAD

**Issue by nightsh** [okfn/crowdsourced-surveys#6]
We need the survey forms to be – ideally – in more languages (English + Swahili). If that is not an option due to platform limitations, then the fallback is to have them in Swahili.

Task is to investigate whether or not the fields are translatable, or if we could create two different forms/surveys that would add their data to the same pool.

**Comment by StephenAbbott** [comment]
Having consulted with our government partners today, I can confirm from them that they would recommend using a mix of English for the field labels and Swahili for any instructions we might provide at the top of the form or in planned SMS comms. 

Will be great to find out what the options are here re: translatable fields vs two separate forms in English and Swahili. Then I could coordinate getting inputs from the partners about which they think would work best.

**Comment by nightsh** [comment]
As per our latest call, we decided that English fields with Swahili descriptions would be acceptable for everyone, as well as a much easier tech implementation. If that's the case, I only need the corresponding Swahili descriptions for our fields (or should I make something up?)

**Comment by StephenAbbott** [comment]
@nightsh I'm sure your Swahili skills would be up to this 😄  but please leave the English form field text for now and I'll explain to partners how we can add Swahili descriptions. Will revisit this issue if/when I have agreed descriptions to add to the form. Thanks!

**Comment by pwalsh** [comment]
Closing. No action required. Will create a new issue if/when we are provided with Swahili descriptions to implement.
