### ISSUE TITLE
"Current location" feature for mobile users

### ISSUE THREAD

**Issue by nightsh** [okfn/crowdsourced-surveys#7]
On mobile browsers, I wasn't able to use/see any "current location" option for the location chooser. We really want that, as it's way more convenient than zooming, panning, tapping etc.

This is to investigate how we can make it appear on mobile devices as well.

**Comment by nightsh** [comment]
Here's the idea of a wrapper page showing up again, as we can make a multi-step form:

1. access location (big button)
2. (if failed) enter location manually
3. all the other questions

Of course, it's just a raw idea and we need to think more about it if we go this way.

**Comment by pwalsh** [comment]
the form has this feature - it is available in the dummy form I set up and shared with you @nightsh

**Comment by nightsh** [comment]
Hah, indeed it does! On my heroku-deployed instance it doesn't, only on desktop. If it's a configuration / deployment thing, that's way easier to fix :) Closing, as we don't need any workarounds for this.

**Comment by pwalsh** [comment]
@nightsh great

**Comment by StephenAbbott** [comment]
@nightsh I've just come from a meeting with government partners in Tanzania and explained our technical plans. They have recommended that some survey respondents may wish to enter a geolocation gathered from a GPS device (such as those which the government have already distributed to many districts) rather than the details collected from the user's mobile browser.

Would we be able default to automatic location collection but give users the option to enter the lat/long or geolocation manually if they wanted to? Let me know if I should raise a new issue seeing as this one is closed.

**Comment by nightsh** [comment]
So, as far as the original issue goes, the "current location" feature is only available via HTTPS. This is not a problem, but it took me a bit to realise it.

As for the GPS devices, are they capable of running a web browser and show up a form they can fill in?

**Comment by StephenAbbott** [comment]
I'm unsure of the capabilities of the GPS devices but am waiting to hear back from our contact at the National Bureau of Statistics about whether these devices will be available to loan to project partners. I will check on the device capabilities.

**Comment by pwalsh** [comment]
@nightsh this all needs a distinct issue, as we are commenting in a closed issue.

I'd go to the original request @StephenAbbott made - can we have a form field for the user to manual add a geolocation. This is very very different from a GPS device running a browser, which I absolutely would not get into. Custom browsers on such devices, if they exist, are usually very very bad and we do not want to be supporting fixes to the ushahidi client for browsers it does not support.

**Comment by nightsh** [comment]
I am not sure if we need a separate issue for this, unless the fields we have for location at the moment do not satisfy the requirement:

![image](https://user-images.githubusercontent.com/1579997/34933932-5f933c16-f9e1-11e7-8d94-e325f882495b.png)

**Comment by pwalsh** [comment]
So, reopened the issue ;).

I agree, this should be enough actually.

**Comment by nightsh** [comment]
I cannot find anything left unsolved about this issue. We have automatic location collection, manual address entry field and manual coordinates fields. I'm gonna close it :)
