### ISSUE TITLE
Feedback option in forms

### ISSUE THREAD

**Issue by StephenAbbott** [okfn/crowdsourced-surveys#8]
Government partners suggested that it would be useful if our mobile survey had an online feedback option. Is it easy enough to add an optional feedback form alongside the required data fields if we wanted to?

**Comment by nightsh** [comment]
Would an optional "feedback" field at the end of the form do the trick?

**Comment by StephenAbbott** [comment]
@nightsh Yes. That would be great

**Comment by nightsh** [comment]
Fixed in [this commit](https://github.com/okfn/crowdsourced-surveys/commit/4a34da1a28161b3d071cec07dbf5f991ff8fa761#diff-f68d06047207ccbbbed3fca027febd0bR319)
